name: build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
      - name: Set env variable
        run: echo "PEARL_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
      - name: Build async rio
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features async-io-rio

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
      - name: Set env variable
        run: echo "PEARL_COMMIT_HASH=$($env:GITHUB_SHA.Substring(0, 8))" >> $env:GITHUB_ENV
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
