name: build

on:
  pull_request:
      types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ master ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Set env variable
        run: export PEARL_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Build   
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all